version: '2'
services:
  app:
    build: .
    ports:
      - 9090:9090
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./:/usr/src/app
    links:
      - mongo
  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017
